bug fix in jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -63,25 +63,26 @@ node {
     }
 
     // ---------- 6. Health Verification ----------
-    // stage('Verify Deployment') {
-    //     withCredentials([file(credentialsId: KUBECONFIG_FILE, variable: 'KUBECONFIG_PATH')]) {
-    //         sh '''
-    //             echo "Port-forwarding and checking /health endpoint..."
-    //             kubectl --kubeconfig $KUBECONFIG_PATH port-forward svc/simple-app-service 7070:80 &
-    //             sleep 5
-    //             STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:7070/health)
-    //             if [ "$STATUS" -ne 200 ]; then
-    //                 echo "Health check failed with status: $STATUS"
-    //                 exit 1
-    //             fi
-    //             echo "Application healthy (HTTP 200)"
-    //         '''
-    //     }
-    // }
+    stage('Verify Deployment') {
+        withCredentials([file(credentialsId: KUBECONFIG_FILE, variable: 'KUBECONFIG_PATH')]) {
+            sh '''
+                echo "Port-forwarding and checking /health endpoint..."
+                kubectl --kubeconfig $KUBECONFIG_PATH port-forward svc/simple-app-service 7070:80 &
+                sleep 5
+                STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:7070/health)
+                if [ "$STATUS" -ne 200 ]; then
+                    echo "Health check failed with status: $STATUS"
+                    exit 1
+                fi
+                echo "Application healthy (HTTP 200)"
+            '''
+        }
+    }
 
     // ---------- 7. Cleanup ----------
     stage('Post-Build Cleanup') {
-        sh 'docker image prune -af'
+    sh "docker rmi ${IMAGE_REPO}:${TAG} || true"
     }
+
 
 } // end of node
